name: wefix4utoday
description: A new Flutter project.
publish_to: 'none' #Remove this line if you wish to publish to pub.dev
version: 1.0.9+26
## Change open file change permission request install package
environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  remixicon: ^1.0.0
  location: ^4.3.0
  geocoding: ^2.0.2
  video_player: ^2.4.5
  video_thumbnail: ^0.4.6
  flutter_sound_lite: ^8.5.0
  permission_handler: ^9.2.0
  step_progress_indicator: ^1.0.2
  file_picker: ^4.5.1
  open_file: ^3.2.1
  google_maps_flutter: ^2.1.3
  dio: ^4.0.6
  record: ^3.0.4
  flutter_rating_bar: ^4.0.0
  skeletons: ^0.0.3
  lottie: ^1.3.0
  search_map_location: ^0.0.5
  expansion_tile_card: ^2.0.0
  file: ^6.0.0
  webview_flutter: ^3.0.4
  firebase_storage: ^11.0.5
  timelines: ^0.1.0
  url_launcher: ^6.1.4
  flick_video_player: ^0.5.0
  map_picker: ^0.0.3
  gallery_saver: ^2.3.2
  sticky_headers: ^0.3.0
  cached_network_image: ^3.2.1
  flutter_cache_manager: ^3.3.0
  geolocator: ^9.0.2
  keyboard_dismisser: ^3.0.0
  audioplayers: ^2.0.0



  ocs_auth:
    git:
      url: https://oauth2:glpat-o79jEubPJUyVZEu4SbjS@gitlab.com/ocs.dev/ocs_auth.git
      ref: wefix4u
  flutter_datetime_picker:
    git: https://github.com/Realank/flutter_datetime_picker.git
  ocs_firebase:
    git: https://oauth2:glpat-o79jEubPJUyVZEu4SbjS@gitlab.com/ocs.dev/ocs_firebase.git
  signalr_flutter:
    git: https://oauth2:glpat-o79jEubPJUyVZEu4SbjS@gitlab.com/ocs.dev/signalr_flutter.git
  google_maps_webservice:
    git: https://oauth2:glpat-o79jEubPJUyVZEu4SbjS@gitlab.com/ocs.dev/google_maps_webservice.git
  flutter_webview_plugin:
    git: https://oauth2:glpat-o79jEubPJUyVZEu4SbjS@gitlab.com/ocs.dev/flutter_webview_plugin.git

dependency_overrides:
  image_picker_android: 0.8.4+13
#  firebase_messaging: 11.2.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.2.16

flutter_native_splash:
  color: "#C13027"
  color_dark: "#C13027"
  image: "assets/logo/logo-white.png"
  android_12:
    icon_background_color: "#C13027"
    icon_background_color_dark: "#C13027"
  web: false


flutter:
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/langs/
    - assets/gifs/
    - assets/logo/
    - assets/banners/

  fonts:
    - family: roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

    - family: robotoMedium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf

    - family: kmFont
      fonts:
        - asset: assets/fonts/battambang_regular.ttf
        - asset: assets/fonts/battambang_bold.ttf

flutter_icons:
  adaptive_icon_background: "#c12f27d9"
  adaptive_icon_foreground: "assets/logo/android_icon.png"
  image_path_android: "assets/logo/android_icon.png"
  image_path_ios: "assets/logo/ios_icon.png"
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true

  #run change package name: flutter pub run change_app_package_name:main com.ocsolution.kys_app
  #run build icon: flutter pub run flutter_launcher_icons:main